// Auto-generated by trickle from runtime type observations
// Generated at 2026-03-11T22:13:11.109Z
// Do not edit manually — re-run `trickle codegen` to update

/**
 * Output type for `calculateTotal` — test-direct-exec-app module, observed in node, 28m ago
 */
export interface CalculateTotalOutput {
  total: number;
  itemCount: number;
  currency: string;
}

export declare function calculateTotal(arg0: CalculateTotalArg0[]): CalculateTotalOutput;

export interface FormatReceiptInputItems {
  name: string;
  price: number;
  quantity: number;
}

/**
 * Input type for `formatReceipt` — test-direct-exec-app module, observed in node, 28m ago
 */
export interface FormatReceiptInput {
  items: FormatReceiptInputItems[];
  total: number;
}

/**
 * Output type for `formatReceipt` — test-direct-exec-app module, observed in node, 28m ago
 */
export interface FormatReceiptOutput {
  lines: string[];
  total: string;
  date: string;
}

export declare function formatReceipt(input: FormatReceiptInput): FormatReceiptOutput;
