# Auto-generated by trickle from runtime type observations
# Generated at 2026-03-11T22:13:11.110Z
# Do not edit manually — re-run `trickle codegen --python` to update

from typing import Any, Awaitable, Callable, Dict, List, Optional, Set, Tuple, TypedDict, Union


# ValidateAndCreate — test-py-deep-app2 module, observed in fastapi, 45m ago
class ValidateAndCreateArgs(TypedDict):
    arg0: str
    arg1: str


class ValidateAndCreateOutput(TypedDict):
    name: str
    email: str
    role: str
    id: float
