# Auto-generated by trickle from runtime type observations
# Generated at 2026-03-11T22:13:11.109Z
# Do not edit manually — re-run `trickle codegen --python` to update

from typing import Any, Awaitable, Callable, Dict, List, Optional, Set, Tuple, TypedDict, Union


# CreateUser — test_py_deep_helpers module, observed in fastapi, 45m ago
class CreateUserArgs(TypedDict):
    arg0: str
    arg1: str


class CreateUserOutput(TypedDict):
    name: str
    email: str
    role: str
    id: float


# ProcessUsers — test_py_deep_helpers module, observed in fastapi, 45m ago
class ProcessUsersArgsArg0(TypedDict):
    name: str
    email: str


class ProcessUsersArgs(TypedDict):
    arg0: List[ProcessUsersArgsArg0]


ProcessUsersOutput = List[Dict[str, Any]]
