# Auto-generated by trickle.auto from runtime observations
# Generated at 2026-03-12T00:59:56.904347+00:00
# Do not edit — types update automatically as your code runs

from typing import Any, Awaitable, Callable, Dict, List, Optional, Set, Tuple, TypedDict, Union, overload


class ApiClient:
    async def get_profile(self, userId: str) -> Awaitable[Dict[str, Any]]: ...
    async def post_comment(self, postId: str, text: str) -> Awaitable[Dict[str, Any]]: ...
    def get_version(self) -> Dict[str, Any]: ...


FetchUserInput = Tuple[str]


class FetchUserOutput(TypedDict):
    id: str
    name: str
    email: str
    active: bool

async def fetch_user(id: str) -> Awaitable[FetchUserOutput]:
    """
    Example::

        >>> fetch_user('u123')
        {'id': 'u123', 'name': 'Alice', 'email': 'alice@example.com', 'active': True}
    """
    ...


class SearchProductsOutputResults(TypedDict):
    id: float
    name: str
    price: float


SearchProductsInput = Tuple[str, float]


class SearchProductsOutput(TypedDict):
    results: List[SearchProductsOutputResults]
    total: float
    query: str

async def search_products(query: str, limit: float) -> Awaitable[SearchProductsOutput]:
    """
    Example::

        >>> search_products('widget', 10)
        {'results': [{...}], 'total': 1, 'query': 'widget'}
    """
    ...


FormatPriceInput = Tuple[float, str]


class FormatPriceOutput(TypedDict):
    formatted: str
    amount: float
    currency: str

def format_price(amount: float, currency: str) -> FormatPriceOutput:
    """
    Example::

        >>> format_price(19.99, '$')
        {'formatted': '$19.99', 'amount': 19.99, 'currency': '$'}
    """
    ...
