// Auto-generated by trickle from runtime type observations
// Generated at 2026-03-11T22:13:11.109Z
// Do not edit manually — re-run `trickle codegen` to update

/**
 * Output type for `greet` — test-watch-app module, observed in node, 37m ago
 */
export interface GreetOutput {
  message: string;
  length: number;
}

export declare function greet(arg0: string): GreetOutput;

/**
 * Output type for `farewell` — test-watch-app module, observed in node, 37m ago
 */
export interface FarewellOutput {
  message: string;
  reason: string;
}

export declare function farewell(arg0: string, arg1: string): FarewellOutput;
