# Auto-generated by trickle from runtime type observations
# Generated at 2026-03-11T22:13:11.109Z
# Do not edit manually — re-run `trickle codegen --python` to update

from typing import Any, Awaitable, Callable, Dict, List, Optional, Set, Tuple, TypedDict, Union


# ValidateEmail — test-py-deep-app module, observed in fastapi, 27m ago
class ValidateEmailArgs(TypedDict):
    arg0: str


class ValidateEmailOutput(TypedDict):
    valid: bool
    reason: None


# FormatUser — test-py-deep-app module, observed in fastapi, 27m ago
class FormatUserArgs(TypedDict):
    arg0: str
    arg1: str
    arg2: str


class FormatUserOutput(TypedDict):
    display_name: str
    email: str
    role: str
    initials: str


# SummarizeUsers — test-py-deep-app module, observed in fastapi, 27m ago
class SummarizeUsersArgsArg0(TypedDict):
    display_name: str
    email: str
    role: str
    initials: str


class SummarizeUsersArgs(TypedDict):
    arg0: List[SummarizeUsersArgsArg0]


class SummarizeUsersOutputRoles(TypedDict):
    admin: float
    user: float


class SummarizeUsersOutput(TypedDict):
    total: float
    roles: SummarizeUsersOutputRoles
    domains: List[str]


# ProcessBatch — test-py-deep-app module, observed in fastapi, 27m ago
class ProcessBatchArgsArg0(TypedDict):
    name: str
    email: str
    role: str


class ProcessBatchArgs(TypedDict):
    arg0: List[ProcessBatchArgsArg0]


class ProcessBatchOutputRoles(TypedDict):
    admin: float
    user: float


class ProcessBatchOutput(TypedDict):
    total: float
    roles: ProcessBatchOutputRoles
    domains: List[str]
